# Generated by Django 2.2.1 on 2019-08-07 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_movimentomensalista'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensalista',
            old_name='valor_mes',
            new_name='valor_mensal',
        ),
    ]
